/**
 * Français — T1 locale, reviewed by a native speaker (Manak).
 *
 * lastSyncedHash: 26447e6cd6f5  ← regenerated by `npm run i18n:check -- --update`
 *   (mismatch = English source changed, re-sync this file)
 */
import type { Messages } from "./en";

const fr: Messages = {
  meta: {
    adminTitle: "LinkBreeze — Admin",
    status: "reviewed" as const,
  },

  localePicker: {
    label: "Langue",
  },

  common: {
    save: "Enregistrer",
    saving: "Enregistrement…",
    cancel: "Annuler",
    delete: "Supprimer",
    close: "Fermer",
    retry: "Réessayer",
    back: "Retour",
    next: "Suivant",
    viewPage: "Voir la page publique",
    saved: "Enregistré !",
  },

  nav: {
    dashboard: "Tableau de bord",
    links: "Liens",
    theme: "Thème",
    settings: "Paramètres",
    profile: "Profil",
    primary: "Principal",
  },

  shell: {
    signedInAs: "Connecté en tant que <b>{name}</b>",
    signOut: "Se déconnecter",
    pagesSection: "Pages",
    demoBannerLead: "Démo en direct.",
    demoBannerVisit: "Voir LinkBreeze",
    demoBannerDeploy: "Déployez votre propre instance",
    livePreview: "Aperçu en direct",
  },

  login: {
    title: "Connexion",
    subtitle: "Connectez-vous pour gérer votre page LinkBreeze",
    username: "Nom d'utilisateur",
    password: "Mot de passe",
    submit: "Se connecter",
    submitPending: "Connexion…",
    invalidCredentials: "Nom d'utilisateur ou mot de passe incorrect.",
    backToPage: "Retour à la page",
    welcomeBack: "Bon retour",
  },

  setup: {

    saving: "Enregistrement…",

    thisIsTheOnlyAccount: "C'est le seul compte. Vous l'utiliserez pour tout gérer.",

    chooseStartingPoint: "Choisissez un point de départ. Vous personnaliserez tout plus tard.",

    importYourExistingPage: "Importer votre page existante",
    welcomeTitle: "Bienvenue sur LinkBreeze",
    createAdminTitle: "Créez votre compte administrateur",
    createAccount: "Créer le compte",
    creatingAccount: "Création du compte…",
    noEmailNote: "30 secondes suffisent. Aucun e-mail requis.",
    networkError: "Erreur réseau. Veuillez réessayer.",
    setUpPage: "Configurez votre page",
    profileStepNote: "C'est ce que verront les visiteurs. Tout est modifiable plus tard.",
    pickTheme: "Choisissez un thème",
    username: "Nom d'utilisateur",
    password: "Mot de passe",
    passwordHint: "Au moins 8 caractères, avec une majuscule et un chiffre.",
    displayName: "Nom affiché",
    displayNamePlaceholder: "Marie Dupont",
    bio: "Bio",
    bioHint: "Une ligne à propos de vous (facultatif)",
    bioPlaceholder: "Designer, développeur, créateur",
    pageUrl: "URL de la page",
    pageUrlHint: "Votre page sera accessible sur /votre-slug",
    finishSetup: "Terminer l'installation",
    allSet: "Tout est prêt !",
    pageLiveDesc: "Votre page est en ligne. Ajoutez votre premier lien pour commencer.",
    goToDashboard: "Aller au tableau de bord",
  },

  dashboard: {

    new: "Nouveau",

    topLinks: "Top liens",

    referrers: "Référents",

    devices: "Appareils",

    countries: "Pays",
    title: "Tableau de bord",
    todayRange: "Aujourd’hui",
    subtitleToday: "Statistiques d’aujourd’hui",
    subtitleTodayRetention: "Statistiques d’aujourd’hui (données conservées {retention} jours)",
    subtitle: "Statistiques des {range} derniers jours",
    subtitleRetention: "Statistiques des {range} derniers jours (données conservées {retention} jours)",
    welcomeTitle: "Bienvenue sur votre tableau de bord",
    welcomeBody: "Votre page est en ligne sur /{slug}. Ajoutez votre premier lien pour commencer à collecter des statistiques.",
    addFirstLink: "Ajouter votre premier lien",
    importExisting: "Importer votre page existante",
    subscribersLink: "{count, plural, one {# abonné} other {# abonnés}}",
    subscribersTitle: "Abonnés e-mail — ouvre Paramètres → Données",
    exportCsv: "Exporter en CSV",
    viewsLabel: "Vues",
    clicksLabel: "Clics",
    uniqueVisitors: "{count} visiteurs uniques",
    linkClicksInRange: "Clics sur le lien sur la période",
    ctrLabel: "Taux de clics",
    ctrHint: "Clics / vues",
    activeLinks: "Liens actifs",
    totalLinks: "{count} au total",
    viewsOverTime: "Vues dans le temps",
    topReferrers: "Sources de trafic",
    referrersDesc: "D'où viennent les vues",
    devicesTitle: "Appareils",
    devicesDesc: "Navigateurs",
    countriesTitle: "Pays",
    countriesDesc: "Localisation des visiteurs",
    noDataYet: "Pas encore de données.",
    noClicksYet: "Aucun clic pour le moment.",
    dailyViewsClicks: "Vues et clics quotidiens",
    topLinksDesc: "{count, plural, one {# lien avec des clics} other {# liens avec des clics}}",
  },

  linksPage: {
    deleting: "Suppression…",
    delete: "Supprimer",

    showMore: "Voir plus ({count} restantes)",

    noIconsMatch: "Aucune icône ne correspond à « {query} ».",

    chooseIcon: "Choisissez une icône…",

    clicksCount: "{count} clics",

    deleteSection: "Supprimer la section",

    willBeRemoved: "« {title} » sera définitivement supprimé. Cette action est irréversible.",

    cancel: "Annuler",

    compact: "Compact",


    richPreview: "Aperçu riche",


    featured: "En vedette",

    active: "Actif",

    iconSection: "Icône",
    iconAutoHint: "Récupère automatiquement le favicon du site.",
    iconModeAuto: "Auto",
    iconModeLucide: "Choisir",
    iconModeCustom: "Téléverser",
    iconUploadSelected: "Sélectionné : {name}",

    utmParameters: "Paramètres UTM",

    schedule: "Programmation",

    showFrom: "Visible à partir du",

    hideAfter: "Masqué après le",

    star: "Star",

    hidden: "Masqué",

    scheduled: "Programmé",

    dropLinksHere: "Déposez vos liens ici",

    links: "Liens",

    addEditAndReorder: "Ajoutez, modifiez et réordonnez les liens de votre page. Regroupez-les sous des en-têtes de section.",

    addSection: "Ajouter une section",

    addLink: "Ajouter un lien",

    noLinksYet: "Aucun lien pour le moment",

    addALinkOrImport: "Ajoutez un lien ou importez depuis une page existante.",

    addYourFirstLink: "Ajoutez votre premier lien",

    importYourExistingPage: "Importer votre page existante",
    ltUrl: "URL",
    ltEmail: "E-mail",
    ltPhone: "Téléphone",
    ltWhatsapp: "WhatsApp",
    ltSms: "SMS",
    ltVcard: "vCard (carte de contact)",
    ltFile: "Téléchargement de fichier",
    ltEmbed: "Intégration (YouTube, Spotify, etc.)",
    ltText: "Popup texte",
    ltLocation: "Localisation",
    ltLocationLabel: "Adresse, lieu ou lien Google Maps",
    phLocation: "Mosquée Koutoubia, Marrakech",
    phPopupText: "Texte long affiché dans la popup quand la carte est tapée.\nPrend en charge **gras**, *italique*, `code`, listes et titres.",
    phCtaUrl: "https://exemple.com/cta (vide = pas de bouton)",
    popupTextLabel: "Texte de la popup",
    ctaLabel: "Libellé du bouton CTA (facultatif)",
    ctaUrlLabel: "URL du CTA",
    phCtaLabel: "Réserver (vide = pas de bouton)",
    phCtaLabelLocation: "Ouvrir dans Google Maps",
    ltEmailLabel: "Adresse e-mail",
    ltPhoneLabel: "Numéro de téléphone",
    ltWhatsappLabel: "Numéro WhatsApp",
    phEmail: "vous@exemple.com",
    phPhone: "+1 (555) 000-0000",
    phUrl: "https://exemple.com",
    title: "Liens",
    subtitle: "Ajoutez, réorganisez et classez les liens de votre page",
    editLink: "Modifier le lien",
    createDescription: "Créez un nouveau lien pour votre page.",
    updateDescription: "Modifiez les détails de ce lien.",
    typeLabel: "Type",
    cardStyle: "Style de carte",
    richHint: "Miniature + aperçu automatique via les Open Graph du lien. Retombe sur le style compact si aucune image n'est trouvée.",
    sectionPlaceholder: "Mes projets",
    iconLabel: "Icône (facultatif)",
    iconShownHint: "Affichée avant le titre de la section sur votre page publique.",
    editSection: "Modifier la section",
    createSectionDesc: "Regroupez des liens sous un en-tête titré sur votre page publique.",
    updateSectionDesc: "Modifiez l'en-tête de cette section.",
    dragReorder: "Glisser pour réorganiser",
    dragReorderSection: "Glisser pour réorganiser la section",
    editSectionAria: "Modifier la section",
    deleteSectionAria: "Supprimer la section",
    openLinkAria: "Ouvrir le lien",
    linkAnalyticsAria: "Statistiques du lien",
    toggleVisibilityAria: "Activer/désactiver la visibilité du lien",
    editLinkAria: "Modifier le lien",
    deleteLinkAria: "Supprimer le lien",
    noSection: "Aucune section",
    removeIcon: "Retirer l'icône",
    searchIcons: "Rechercher des icônes…",
    deleteLinkTitle: "Supprimer le lien ?",
    deleteSectionTitle: "Supprimer la section ?",
    utmSource: "Source",
    utmMedium: "Média",
    utmCampaign: "Campagne",
    utmTerm: "Terme (facultatif)",
    utmContent: "Contenu (facultatif)",
    url: "URL",
    title_field: "Titre",
    titlePlaceholder: "Mon site web",
    description: "Description (facultatif)",
    descriptionPlaceholder: "Tous mes liens au même endroit",
    animatedGif: "URL du GIF animé",
    thumbnail: "Miniature URL (facultatif)",
    icon: "Icône + titre",
    iconHint: "Icône + titre. Simple et épuré.",
    customUrl: "URL personnalisée",
    imageUrl: "URL de l'image",
    section: "Section",
    duplicate: "Dupliquer",
  },

  profile: {

    uploadImage: "Envoyer une image",

    thisInformationAppearsOnYourPublicPage: "Ces informations apparaissent sur votre page publique.",

    addAPlatform: "Ajouter une plateforme",

    uploading: "Envoi en cours…",

    uploadBanner: "Envoyer une bannière",

    uploadedCheck: "Envoyé ✓",

    customUrl: "URL personnalisée",
    availableForWork: "✨ Disponible pour des missions",
    title: "Profil",
    details: "Détails",
    identityDesc: "Votre identité publique",
    subtitle: "Votre identité publique — nom, bio, avatar et réseaux sociaux",
    displayName: "Nom affiché",
    displayNamePlaceholder: "Jane Doe",
    bio: "Bio",
    bioPlaceholder: "Une courte description",
    avatar: "URL de l'avatar",
    avatarHint: "Max 2 Mo. JPG, PNG, WebP.",
    banner: "Image de bannière (facultatif)",
    badge: "Texte du badge (facultatif)",
    socialLinks: "Réseaux sociaux",
    socialLinksHint:
      "Les icônes apparaissent au-dessus de vos cartes de liens. Touchez une plateforme pour l'ajouter.",
    removeSocial: "Retirer ce réseau",
    saveProfile: "Enregistrer le profil",
    savedToast: "Enregistré !",
  },

  pages: {

    thePageRsquoSLinksAreDeletedWithItInclud: "Les liens de la page sont supprimés avec elle, y compris leur historique de clics.",

    linksMoveToYourDefaultPageUncategorizedN: "Les liens passent à votre page par défaut, sans catégorie. Rien n'est perdu.",

    backToLinks: "Retour aux liens",

    newPage: "Nouvelle page",

    slugHint: "Le slug est le chemin URL. Vous personnaliserez le reste plus tard.",

    slugCharsHint: "Lettres, chiffres et tirets. Ceci devient votre URL : /music",

    keepTheLinks: "Garder les liens",


    deleteEverything: "Tout supprimer",


    cancel: "Annuler",
    title: "Pages",
    newPageDesc: "Créez une nouvelle page avec ses propres liens, profil et thème.",
    detailsTitle: "Détails de la page",
    titleOptional: "Titre (facultatif)",
    titlePagePlaceholder: "Ma page musique",
    bioOptional: "Bio (facultatif)",
    bioPlaceholder: "Une courte description",
    creating: "Création…",
    createDescription: "Chaque page est un mini-profil complet avec ses propres liens.",
    slug: "Slug de la page",
    deletePageTitle: "Supprimer la page ?",
    create: "Créer la page",
  },

  theme: {
    customiseTitle: "Personnaliser {name}",
    editingCustom: "Modification d'un thème personnalisé",
    presetCopyNote: "Préréglage — l'enregistrement crée votre propre copie",
    saving: "Enregistrement…",
    saveChanges: "Enregistrer les modifications",
    saved: "Enregistré",
    sharedPresetWarning: "{name} est un préréglage partagé — le modifier relookerait toutes les pages qui l'utilisent. Enregistrez plutôt vos personnalisations dans un nouveau thème.",
    creating: "Création…",
    createSave: "Créer et enregistrer",
    delete: "Supprimer",
    themesUseIt: "{count} thème(s) l'utilisent ({names}) et reviendront à Inter.",
    deleteFont: "Supprimer la police",
    deleteNamedTheme: "Supprimer « {name} »",
    builtinNoDelete: "Les thèmes intégrés ne peuvent pas être supprimés",
    createsCopyOf: "Crée une copie modifiable de",
    duplicating: "Duplication…",
    duplicate: "Dupliquer",
    uploading: "Envoi en cours…",
    uploadMedia: "Envoyer",
    uploadFont: "Envoyer une police",
    usedByThemes: "utilisée par {count} thèmes",
    cancel: "Annuler",
    import: "Importer",
    export: "Exporter",

    thisActionCannotBeUndoneTheThemeWillBePe: "Cette action est irréversible. Le thème sera définitivement supprimé.",

    chooseAPresetOrFullyCustomiseYourPage: "Choisissez un préréglage ou personnalisez entièrement votre page",

    everyChangePreviewsLiveChangesApplyOnSav: "Chaque changement s'affiche en direct. Les modifications s'appliquent à l'enregistrement.",

    colorsCommaSeparated: "Couleurs (séparées par des virgules)",

    setTheBannerImageOnTheProfilePageBannerI: "Définissez l'image de bannière sur la page Profil (champ Image de bannière). Les mises en page Hero et Bannière l'utilisent comme couverture.",

    auroraIsDrivenByYourColorsAccentPrimaryA: "Aurora est pilotée par vos couleurs : l'accent (primaire) et la secondaire teintent les blobs animés, et la première couleur de fond définit la base.",

    uploadMediaOrPasteAUrlToUnlockDisplayCon: "Téléversez un média ou collez une URL pour débloquer les contrôles d'affichage (ajustement et point focal).",

    howTheMediaFillsThePage: "Comment le média remplit la page",

    downloadAThemeAsAJsonFileToBackItUpOrSha: "Téléchargez un thème en fichier .json pour le sauvegarder ou le partager, puis importez-le sur une autre instance.",

    nameOfTheCopy: "Nom de la copie",

    theOriginalStaysUntouched: "L'original reste inchangé.",

    importAmpExport: "Import et export",

    noThemesUseThisFont: "Aucun thème n'utilise cette police.",

    onlyUploadFontsYouHaveTheLicenseToUseUpl: "N'envoyez que des polices dont vous avez la licence. L'envoi est unique ; vous pourrez ensuite la choisir pour n'importe quel thème.",

    auto: "Auto",



    focalHint: "Glissez le point pour définir le point focal — la partie qui reste visible quand les écrans la recadrent.",






    deleteFontTitle: "Supprimer « {name} » ?",



    kb: "Ko",

    center: "Centre",
    // option labels (values are i18n keys; see theme-constants.ts)
    tabBackground: "Arrière-plan",
    tabTypography: "Typographie",
    tabLinks: "Liens",
    tabProfile: "Profil",
    tabEffects: "Effets",
    bgSolid: "Unie",
    bgGradient: "Dégradé",
    bgRadial: "Radial",
    bgMesh: "Mesh",
    bgAurora: "Aurore",
    bgAnimatedGradient: "Dégradé animé",
    bgImage: "Image",
    bgVideo: "Vidéo",
    bgGif: "GIF animé",
    lsPill: "Pilule",
    lsRounded: "Arrondi",
    lsSharp: "Net",
    lsGlass: "Verre",
    lsOutline: "Contour",
    lsNeon: "Néon",
    lsPixel: "Pixel",
    lsGel: "Gel",
    shadowNone: "Aucune",
    shadowSubtle: "Discrète",
    shadowSoft: "Douce",
    shadowMedium: "Moyenne",
    shadowStrong: "Forte",
    hoverLift: "Élévation",
    hoverScale: "Agrandissement",
    hoverGlow: "Lueur",
    hoverNone: "Aucun",
    angle90: "90° (horizontal)",
    angle135: "135° (diagonale)",
    angle160: "160° (incliné)",
    angle180: "180° (vertical)",
    weightLight: "Léger",
    weightRegular: "Regular",
    weightMedium: "Moyen",
    weightSemibold: "Semibold",
    weightBold: "Gras",
    sizeSm: "Petit",
    sizeMd: "Moyen",
    sizeLg: "Grand",
    alignLeft: "Gauche",
    alignCenter: "Centré",
    alignRight: "Droite",
    densityCompact: "Compacte",
    densityNormal: "Normale",
    densityRelaxed: "Espacé",
    revealLift: "Élévation (montée)",
    revealScale: "Agrandissement (progressif)",
    revealFadeUp: "Fondu vers le haut",
    revealSlideIn: "Glissement",
    revealZoomIn: "Zoom avant",
    revealBlurIn: "Flou vers net",
    revealNone: "Aucune",
    avCircle: "Cercle",
    avSquircle: "Arrondi carré",
    avRounded: "Carré arrondi",
    avSquare: "Carré",
    borderSolid: "Accent uni",
    borderGradient: "Dégradé",
    borderGlow: "Lueur",
    borderRing: "Anneau (décalé)",
    borderNone: "Aucune",
    layoutClassic: "Classique (avatar + nom + bio)",
    layoutHero: "Hero (bannière image, nom superposé)",
    layoutBanner: "Bannière (large image au-dessus du classique)",
    textAnimNone: "Aucune",
    textAnimTypewriter: "Machine à écrire (nom affiché)",
    textAnimGradientFlow: "Flux de dégradé (nom affiché)",
    focalCover: "Remplir",
    focalCoverTitle: "Remplit la page en rognant les bords si nécessaire",
    focalContain: "Contenir",
    focalContainTitle: "Affiche toute l'image, avec bandes si nécessaire",
    focalTile: "Mosaïque",
    focalTileTitle: "Répète à taille naturelle — pour motifs et textures",
    mockWebsite: "Mon site",
    demoAvatarInitial: "A",
    demoName: "Votre nom",
    demoBio: "Designer & créateur",
    mockVideo: "Dernière vidéo",
    title: "Thème",
    subtitle: "Concevez l'apparence de votre page publique",
    activeTheme: "Thème actif",
    layout: "Mise en page",
    profileLayout: "Mise en page du profil",
    colors: "Couleurs",
    accent: "Couleur d'accent (principale)",
    secondary: "Secondaire",
    text: "Texte",
    background: "Arrière-plan",
    cardBackground: "Arrière-plan des cartes",
    cardBorder: "Bordure des cartes",
    cardStyle: "Style de carte",
    linkStyle: "Style des liens",
    buttonSize: "Taille des boutons",
    cornerRadius: "Arrondi des coins",
    containerWidth: "Largeur du conteneur",
    borderWidth: "Épaisseur de bordure",
    effects: "Effets",
    hoverEffect: "Effet au survol",
    revealAnimation: "Animation d'apparition",
    noiseTexture: "Texture de bruit",
    glassBlur: "Flou translucide",
    glow: "Éclat",
    glowColor: "Couleur de l'éclat",
    overlayColor: "Couleur du calque",
    overlayOpacity: "Opacité du calque",
    opacity: "Opacité",
    typography: "Typographie",
    fontScale: "Échelle de police",
    letterSpacing: "Espacement des lettres",
    cardFontToggle: "Utiliser une police différente pour les cartes",
    cardFontLabel: "Police des cartes",
    displayNameAnimation: "Animation du nom affiché",
    avatarShape: "Forme de l'avatar",
    avatarBorder: "Bordure de l'avatar",
    avatarSize: "Taille de l'avatar",
    floatingAvatar: "Avatar flottant",
    badge: "Badge",
    deleteTheme: "Supprimer le thème",
    duplicateTheme: "Dupliquer le thème",
    importExport: "Import et export",
    previewImport: "Prévisualiser l'import",
    pickTheme: "Choisissez un thème",
    mutedText: "Texte atténué",
    hideAfter: "Masquer après",
    showFrom: "Afficher à partir de",
    alignment: "Alignement",
    angle: "Angle",
    density: "Densité",
    shadow: "Ombre",
    weight: "Graisse",
    typeLabel: "Type",
    imageFit: "Cadrage de l'image",
    imageUrl: "URL de l'image",
    videoUrl: "URL vidéo (.mp4 / .webm)",
    animatedGif: "URL du GIF animé",
    displayNameOptional: "Nom affiché (facultatif)",
    newThemeName: "Nom du nouveau thème",
    themeCopyPlaceholder: "Mon thème (copie)",
    selectPlaceholder: "Sélectionner…",
    dupFailed: "Échec de la duplication du thème. Veuillez réessayer.",
    delFailed: "Échec de la suppression du thème. Veuillez réessayer.",
    deleting: "Suppression…",
    importFailed: "Échec de l'import",
    importing: "Import…",
    chooseJsonFile: "Choisir un fichier JSON…",
    saveAsOwn: "Enregistrer comme votre propre thème ?",
    focalPoint: "Point focal — glissez ou utilisez les flèches",
    recenter: "Recentrer",
    recenterFocal: "Recentrer le point focal",
    customizerSections: "Sections du personnalisateur",
    applying: "Application…",
    deleteCustomConfirm: "Supprimer ce thème personnalisé ?",
    avatarHint: "Max 2 Mo. JPG, PNG, WebP.",
    gifHint: "Max 2 Mo. Gardez des boucles courtes — les gros GIFs pèsent lourd pour les visiteurs mobiles.",
    videoHint: "Max 5 Mo, boucle en lecture automatique sans son. Repli : vos couleurs d'arrière-plan s'affichent si la vidéo ne charge pas.",
    profileSectionLabel: "Profil",
  },

  settings: {
    title: "Paramètres",
    qrTitle: "QR Code",
    qrCardDesc: "Personnalisez et téléchargez le QR pour /{slug}. Scannez pour ouvrir votre page publique — utile sur print ou écrans.",
    subtitle:
      "Configuration de la page, apparence et sécurité du compte pour /{slug}",

    tabs: {
      general: "Général",
      integration: "Intégration",
      appearance: "Apparence",
      security: "Sécurité",
      data: "Données",
    },

    language: {
      title: "Langue",
      description:
        "Langue de l'interface d'administration. Votre page publique n'est pas concernée.",
    },

    visibility: {
      title: "Visibilité dans les moteurs de recherche",
      description:
        "Contrôle si les moteurs de recherche peuvent référencer votre page publique.",
      visibleLabel: "Visible",
      visibleHint: "Votre page peut apparaître dans les résultats de recherche et le sitemap.",
      hiddenLabel: "Masquée",
      hiddenHint:
        "La page reste accessible, mais demande aux moteurs de ne pas l'indexer et la retire du sitemap.",
      footnote:
        "Le masquage repose sur la coopération des moteurs ; les pages déjà indexées peuvent mettre des semaines à disparaître.",
    },

    general: {
      privacyPlaceholder: "# Politique de confidentialité\\n\\nCette page utilise des statistiques respectueuses de la vie privée...",
      saving: "Enregistrement…",
      saveGeneral: "Enregistrer les réglages généraux",
    footerPlaceholder: "© 2026 Camille Martin",
      title: "Général",
      description: "Slug, titre, métadonnées SEO, pied de page et politique de confidentialité.",
      pageSlug: "Slug de la page",
      slugHintRich: "Votre page publique est accessible sur <code>/{slug}</code>",
      viewPublicPage: "Voir la page publique",
      pageTitle: "Titre de la page (SEO)",
      pageTitlePlaceholder: "Marie Dupont — Liens",
      seoDescription: "Description SEO",
      seoPlaceholder: "Tous mes liens au même endroit",
      footerText: "Texte du pied de page (facultatif)",
      privacyPolicy: "Politique de confidentialité (facultatif)",
      privacyHintRich: "Laissez vide pour générer automatiquement depuis les réglages de votre page. Les visiteurs y accèdent toujours via <code>/{slug}/privacy</code>. Markdown pris en charge (titres, listes, <strong>gras</strong>, <em>italique</em>, <code>code</code>).",
      save: "Enregistrer les paramètres généraux",
    },

    integration: {
      saving: "Enregistrement…",
      saveIntegration: "Enregistrer les réglages d'intégration",
      title: "Intégration",
      description: "Statistiques, CSS personnalisé et collecte d'e-mails.",
      analyticsScript: "Script d'analyse (facultatif)",
      analyticsHintRich: "Collez un extrait de script pour Plausible, Umami, Matomo, Google Analytics, etc. Ajoutez le domaine du fournisseur à <code>EXTRA_SCRIPT_SRC</code> dans votre .env pour que la CSP autorise son chargement.",
      customCss: "CSS personnalisé (facultatif)",
      customCssHintRich: "CSS brut injecté dans une balise <code>&lt;style&gt;</code> sur votre page publique.",
      consentHintRich: "Affiché à côté de la case de consentement sur votre formulaire d'inscription. Laissez vide pour la valeur par défaut : <em>J'accepte de recevoir des e-mails et je sais que je peux me désinscrire à tout moment.</em>",
      consentPlaceholder:
        "J'accepte de recevoir des e-mails et je sais que je peux me désinscrire à tout moment.",
      enabled: "Activé",
      disabled: "Désactivé",
      emailCapture: "Abonnement e-mail",
      emailCaptureHintRich: "Affiche un formulaire d'inscription en bas de votre page publique. Les abonnés sont stockés dans votre base de données et exportables en CSV.",
      consentText: "Texte de consentement e-mail",

      save: "Enregistrer les paramètres d'intégration",
    },

    appearance: {
      saving: "Enregistrement…",
      saveAppearance: "Enregistrer l'apparence",
      title: "Apparence",
      description: "Favicon et réglages visuels par page.",
      activeTheme: "Thème actif",
      favicon: "Favicon",
      faviconHint: ".ico, .png, .svg, .gif ou .webp (max 1 Mo).",
      currentFavicon: "Favicon actuelle",
      uploadFavicon: "Téléverser un favicon",
      uploading: "Téléversement…",
      save: "Enregistrer l'apparence",
    },

    security: {

      updatePassword: "Mettre à jour le mot de passe",

      updating: "Mise à jour…",

      changePassword: "Changer le mot de passe",


      description: "Changez votre mot de passe administrateur.",
      desc: "Mettez à jour votre mot de passe administrateur.",
      currentPassword: "Mot de passe actuel",
      newPassword: "Nouveau mot de passe",
      passwordHint: "Au moins 8 caractères avec une majuscule et un chiffre.",
      updated: "Mot de passe mis à jour.",
    },

    data: {
      noSubscribers: "Aucun abonné pour le moment. Votre formulaire d'inscription est en ligne sur votre page publique.",
      clearAll: "Tout effacer",
      selectAllSubscribers: "Sélectionner tous les e-mails",
      selectSubscriber: "Sélectionner l’e-mail",
      deleteSelected: "Supprimer la sélection ({count})",
      deleteAction: "Supprimer",
      deleteSelectedTitle: "Supprimer les e-mails sélectionnés ?",
      deleteConfirmSelected: "Supprimer définitivement les {count} e-mails sélectionnés ? Cette action est irréversible.",
      selectedSubscribersDeleted: "Les e-mails sélectionnés ont été supprimés.",
      allSubscribersCleared: "Tous les e-mails de cette page ont été supprimés.",
      subscriberDeleteFailed: "Impossible de supprimer les e-mails. Réessayez.",
      subscriberCount: "{count, plural, =1 {# abonné.} other {# abonnés.}}",
      deleteConfirmIcu: "Supprimer définitivement les {count} abonnés ? Action irréversible.",
      restoring: "Restauration…",
      clearing: "Effacement…",

      clearAllAnalytics: "Effacer toutes les statistiques",

      restoreBackup: "Restaurer une sauvegarde",

      data: "Données",

      retentionHint2: "Sauvegardez ou restaurez votre contenu et contrôlez la conservation des statistiques.",

      emailSubscribers: "Abonnés e-mail",

      subscribersDesc: "Les adresses e-mail apparaissent ici quand des visiteurs s'abonnent sur votre page publique.",

      exportBackup: "Exporter une sauvegarde",

      retentionHint: "Les statistiques plus anciennes sont supprimées automatiquement. Par défaut 90 jours — mettez 0 pour tout conserver.",

      checkReleases: "Consultez les nouvelles versions sur le tableau de bord.",

      restoreWarning: "Cela REMPLACERA tous les liens, le profil, les réglages et les thèmes actuels. Cette action est irréversible.",

      restore: "Restaurer",

      clearWarning: "Supprimer définitivement TOUTES les statistiques (vues + clics) et réinitialiser les compteurs de clics. Action irréversible.",

      clear: "Effacer",

      cancel: "Annuler",
      backupRestored: "Sauvegarde restaurée.",
      restoreFailed: "Échec de la restauration.",
      keepForeverHint: "0 = conserver indéfiniment",
      analyticsCleared: "Statistiques effacées.",
      consentYes: "Oui",
      notAvailable: "N/D",
      title: "Données",
      description: "Exportez, sauvegardez et gérez vos données.",
      exportCsv: "Exporter en CSV",
      retentionLabel: "Conservation des statistiques (jours)",
      updateNotifications: "Notifications de mise à jour",
      restoreTitle: "Restaurer la sauvegarde ?",
      clearAnalyticsTitle: "Effacer toutes les statistiques ?",
      clearTitle: "Effacer tous les abonnés ?",
      colEmail: "E-mail",
      colSubscribed: "Inscrit le",
      colConsent: "Consentement",
    },

    qr: {
      saving: "Enregistrement…",

      saveStyle: "Enregistrer le style",

      savedBang: "Enregistré !",

      codeColor: "Couleur du code",

      backgroundColor: "Arrière-plan",

      themeColors: "Couleurs du thème",

      logoHint: "Avec un logo, la correction d'erreur passe à High pour que le code reste scannable.",

      exportSize: "Taille d'export PNG",

      px: "px",

      svg: "SVG",

      png: "PNG",

      reset: "Réinitialiser",
      styleLabel: "Style du QR code",





      colorLabel: "Couleur du QR code",
      bgLabel: "Couleur d'arrière-plan du QR",
      centerLogo: "Logo central",
      previewAlt: "Aperçu du QR code",
    },
  },

  pageSwitcher: {
    newPage: "Nouvelle page",
    deletePage: "Supprimer la page {name}",
    viewPage: "Voir la page publique /{slug}",
    makeDefault: "Définir {name} comme page par défaut",
    nowDefault: "« {name} » est maintenant votre page par défaut",
  },

  linkDetail: {
    backToLinks: "Retour aux liens",
    clicksOverTime: "Clics dans le temps",
    dailyClicks: "Clics quotidiens pour ce lien",
    topReferrers: "Principaux référents",
    referrersDesc: "D'où viennent ces clics",
    noReferrerData: "Pas encore de données de référents.",
  },

  migration: {

    socialProfilesInstagramYoutubeEtcAreAuto: "Les profils sociaux (Instagram, YouTube, etc.) sont détectés automatiquement et ajoutés comme icônes sociales.",


    reviewTheExtractedLinksBelowUncheckAnyYo: "Vérifiez les liens extraits ci-dessous. Décochez ceux que vous ne voulez pas importer.",

    noLinksFoundOnThisPageTryADifferentUrl: "Aucun lien trouvé sur cette page. Essayez une autre URL.",

    linktreeBentoLnkBioTapLinkHoppLittlelink: "Linktree, Bento, Lnk.bio, Tap.link, Hopp, LittleLink, Beacons, Solo.to, et plus.",

    importLinksFromLinktreeBentoLnkBioLittle: "Importez des liens depuis Linktree, Bento, Lnk.bio, LittleLink ou toute autre page link-in-bio.",


    importComplete: "Import terminé",

    importedCounts: "{links} liens importés",

    andSocial: "et {count} profils sociaux",

    intoThisPage: "dans cette page.",

    iconFallbackWarning: "{count, plural, one {# lien importé n'a pas pu récupérer l'icône de son site et affichera une lettre de remplacement.} other {# liens importés n'ont pas pu récupérer l'icône de leur site et afficheront une lettre de remplacement.}}",

    iconFallbackHint: "Modifiez puis réenregistrez ces liens pour relancer la récupération de l'icône.",

    importAnother: "Importer une autre page",

    viewLinks: "Voir les liens",



    back: "Retour",

    importing: "Import en cours...",

    migrationWizard: "Assistant de migration",


    url: "URL",

    file: "Fichier",

    fetchingLinks: "Récupération des liens...",

    fetchLinks: "Récupérer les liens",

    parsingFile: "Analyse du fichier...",

    uploadExtract: "Envoyer et extraire",

    supportedPlatforms: "Plateformes prises en charge :",



    linksCount: "Liens ({count})",

    socialProfilesCount: "Profils sociaux ({count})",
    extractFailed: "Échec de l'extraction des liens",
    importFailed: "Échec de l'import",
    pageUrlLabel: "URL de la page",
    previewImport: "Prévisualiser l'import",
    fileLabel: "Fichier HTML ou JSON",
    fileHint: "Enregistrez une page concurrente en HTML, ou téléversez un export JSON.",
  },

  onboarding: {
    heading: "Premiers pas",
    subtitleStart: "Quelques étapes pour préparer votre page.",
    subtitleProgress: "{done} sur {total} terminées — continuez !",
    setProfile: "Définissez votre nom et votre bio",
    setTheme: "Choisissez un thème",
    setLinks: "Ajoutez votre premier lien",
    dismiss: "Ignorer",
  },

  preview: {
    refresh: "Actualiser l'aperçu",
    openNewTab: "Ouvrir dans un nouvel onglet",
    close: "Fermer l'aperçu",
    livePreview: "Aperçu en direct",
  },

  errors: {
    errorBoundary: {
      title: "Une erreur est survenue",
      description:
        "Une erreur inattendue s'est produite au chargement de cette page. Réessayez, et si le problème persiste, consultez les logs du serveur ou redémarrez le conteneur.",
      errorId: "ID d'erreur",
      retry: "Réessayer",
      backToDashboard: "Retour au tableau de bord",
    },
    somethingWentWrong: "Une erreur est survenue. Veuillez réessayer.",
    uploadFailed: "Échec du téléversement. Veuillez réessayer.",
    invalidCredentials: "Nom d'utilisateur ou mot de passe incorrect.",
    unauthorized: "Non autorisé",
    invalidInput: "Entrée invalide",
    invalidJson: "JSON invalide",
    notFound: "Introuvable",
    usernameRequired: "Le nom d'utilisateur est requis",
    usernameTooShort: "Le nom d'utilisateur doit contenir au moins 3 caractères",
    usernameChars: "Le nom d'utilisateur ne peut contenir que des lettres, des chiffres, des points, des tirets et des underscores",
    passwordRequired: "Le mot de passe est requis",
    invalidEmail: "Veuillez saisir une adresse e-mail valide",
    slugRequired: "Le slug est requis",
    slugCharsUnderscore: "Le slug ne peut contenir que des lettres, des chiffres, des tirets et des underscores",
    slugTooLong: "Le slug doit contenir 80 caractères ou moins",
    titleRequired: "Le titre est requis",
    invalidIconName: "Nom d'icône invalide",
    invalidPosition: "Position invalide",
    rateLimited: "Trop de requêtes. Réessayez dans {seconds} s.",
    demoReadOnly: "Ceci est une démo en lecture seule. Déployez votre propre instance pour effectuer des modifications.",
    setupCompleted: "L'installation a déjà été effectuée",
    setupFailed: "Une erreur est survenue pendant l'installation. Veuillez réessayer.",
    usernameTaken: "Ce nom d'utilisateur est déjà pris",
    pageDeleteFailed: "Une erreur est survenue lors de la suppression de la page. Veuillez réessayer.",
    slugExists: "Une page avec ce slug existe déjà",
    defaultPageProtected: "La page par défaut ne peut pas être supprimée",
    pageNotFound: "Page introuvable",
    invalidPageId: "ID de page invalide",
    missingPageId: "ID de page manquant",
    linkNotFound: "Lien introuvable",
    invalidLinkId: "ID de lien invalide",
    missingLinkId: "ID de lien manquant",
    invalidSectionId: "ID de section invalide",
    missingSectionId: "ID de section manquant",
    invalidOrderPayload: "Ordre invalide",
    urlRequired: "L'URL est requise",
    urlSchemeNotAllowed: "Ce type de lien n'autorise pas ce schéma d'URL",
    themeNameExists: "Un thème avec ce nom existe déjà",
    themeNotFound: "Thème introuvable",
    invalidThemeId: "ID de thème invalide",
    builtinThemeProtected: "Les thèmes intégrés ne peuvent pas être supprimés",
    activeThemeProtected: "Impossible de supprimer le thème actif",
    noActiveTheme: "Aucun thème actif",
    noThemeToCustomize: "Aucun thème à personnaliser",
    noThemeToDuplicate: "Aucun thème à dupliquer",
    noFile: "Aucun fichier fourni",
    fileRequired: "Fichier requis",
    fileEmpty: "Le fichier est vide",
    fileNotImage: "Le fichier doit être une image",
    fileNotVideo: "Le fichier doit être une vidéo",
    fileTooLarge1: "Fichier trop volumineux (max 1 Mo)",
    fileTooLarge2: "Fichier trop volumineux (max 2 Mo)",
    fileTooLargeMb: "Fichier trop volumineux (max {mb} Mo)",
    fileTooLarge5: "Fichier trop volumineux (max 5 Mo)",
    unsupportedFileType: "Type de fichier non pris en charge",
    unsupportedMedia: "Type de fichier non pris en charge. Utilisez une image ou une vidéo .mp4/.webm",
    unsupportedFavicon: "Type de fichier non pris en charge. Utilisez .ico, .png, .svg, .gif ou .webp",
    unsupportedFont: "Type de fichier non pris en charge. Utilisez .woff2 ou .woff",
    fontNotFound: "Police introuvable",
    invalidFontId: "ID de police invalide",
    fontGone: "Cette police personnalisée n'existe plus",
    invalidFontFile: "Fichier de police invalide (woff2 ou woff attendu)",
    fontTooLarge: "Police intégrée trop volumineuse (max 2 Mo)",
    fontStoreFailed: "Impossible d'enregistrer le fichier de police. Vérifiez l'espace disque et les permissions.",
    fontRestoreFailed: "Impossible de restaurer le fichier de police intégré",
    noBackupFile: "Aucun fichier de sauvegarde fourni",
    invalidBackup: "Sauvegarde LinkBreeze invalide",
    backupMalformedData: "Sauvegarde contenant des données malformées — les lignes ne correspondent pas au schéma attendu",
    backupMalformedSections: "Sauvegarde contenant des sections malformées",
    backupMalformedFonts: "Sauvegarde contenant des polices personnalisées malformées",
    restoreIncompatible: "Échec de la restauration — la sauvegarde est peut-être incompatible",
    invalidImportData: "Données d'import invalides",
    invalidJsonFile: "Fichier JSON invalide",
    unsupportedImportFile: "Seuls les fichiers HTML et JSON sont pris en charge",
    importCooldown: "Veuillez patienter 30 secondes entre deux imports",
    fetchFailed: "Impossible de récupérer la page",
    parseFailed: "Impossible d'analyser le fichier",
    targetPageNotFound: "Page cible introuvable",
    wrongCurrentPassword: "Mot de passe actuel incorrect",
    passwordTooShort: "Le mot de passe doit contenir au moins 8 caractères",
    passwordNeedsUpper: "Le mot de passe doit contenir au moins une majuscule",
    passwordNeedsLower: "Le mot de passe doit contenir au moins une minuscule",
    passwordNeedsNumber: "Le mot de passe doit contenir au moins un chiffre",
    displayNameRequired: "Le nom affiché est requis",
    slugChars: "Le slug ne peut contenir que des lettres, des chiffres et des tirets",
    nameRequired: "Le nom est requis",
    invalidDeleteMode: "Mode de suppression invalide",
    invalidSubmission: "Soumission invalide",
    customFont: "Police personnalisée",
  },

  update: {
    available: "LinkBreeze v{version} est disponible",
    running: "Vous utilisez la v{version}",
    viewReleaseNotes: "Voir les notes de version",
    checkAgain: "Vérifier à nouveau",
    dismiss: "Ignorer la notification de mise à jour",
  },
};

export default fr;
